DEBUG_LIST = ["2W19KS75"]
BAY_STATUS_LIST = [ "making the bay great again",
                    "adding to the clutter",
                    "doing stuff and things and such",
                    "avoiding assignments",
                    "making the norse god vidar proud",
                    "why don't I have 40 apple interviews yet?",
                    "Not eating",
                    "Sleeping in the comfy leather chair thing",
                    "juggling ignition spacers",
                    "what if we stored all of our fill hoses in a linked list?",
                    ":rocket::rocket::rocket::rocket::rocket::rocket::rocket::rocket::rocket::rocket:",
                    "knolling",
                    "soldering dangerously"]
BAY_LEAVE_STATUS_LIST = ["went home",
                "not in the bay anymore",
                "doing homework or reddit or something",
                "off having adventures and slaying dragons",
                "in the bay only in spirit",
                "oh right, I still have classes",
                "struggling to explain to normies why I spend so much time at rocketry",
                "stripping for money to buy better wire strippers",
                "praying for successful ignition",
                "moved to iceland. Became a shepherd."]
BAY_LEAVE_EMOJI_LIST = [":feelsbadman:",
                        ":rip:",
                        ":sob:",
                        ":robin:"]
ignore_list = [] # Users in this list (identified by user ID) will not show up in "/bay who"
agenda_react_emojis = [":acetone:", ":actually_ham:", ":adam:", ":addreaction:", ":alex:", ":alsoham:", ":anarchist:", ":aristotle:", ":axe:", ":banan:", 
                        ":beret:", ":blackspace:", ":bone_ana:", ":broom:", ":chill:", ":cinnamon:", ":comrade:", ":cosin:", ":cute:", ":cuter:", ":cutest:", 
                        ":dab:", ":damn:", ":david:", ":diode:", ":doris:", ":dragoncurve:", ":drill:", ":em:", ":em1:", ":em2:", ":em3:", ":em4:", ":emily:", 
                        ":failfish:", ":feelsbadman:", ":fox:", ":fpaacs:", ":gain:", ":god:", ":gold:", ":goodstuff:", ":goose:", ":greatstuff:", ":ham:", 
                        ":hellothere:", ":hilbert:", ":hilbertcurve:", ":hilberto:", ":hilly:", ":hotstrippers:", ":hussein:", ":infinity:", ":jacob:", ":julia:", 
                        ":kappa:", ":kenneth:", ":koch:", ":lad:", ":lambda:", ":logo:", ":logo2:", ":mandelbrot:", ":mandelbrotrainbow:", ":matrix:", ":maxq:", 
                        ":maxrobin:", ":mcteerts:", ":menger:", ":meowth:", ":miranda:", ":monkas:", ":newhire:", ":nick:", ":nina:", ":ninasback:", ":nofrills:", 
                        ":noosejs:", ":nugget:", ":nylon:", ":ohgod:", ":opvote:", ":pain:", ":parrot:", ":partyparrot:", ":paylad:", ":pita:", ":pjsalt:", ":pogchamp:", 
                        ":polymethlymethacrylate:", ":praxair:", ":psi:", ":q:", ":rip:", ":robin:", ":ryan:", ":ryerson:", ":sadparrot:", ":sanic:", ":shufflelogo:", ":shufflelogo2:", 
                        ":shuffleparrot:", ":shuffleparrot2:", ":sierpinski:", ":sin:", ":siren:", ":sledge:", ":slowpoke:", ":subtle:", ":syzygy:", ":thonking_foce:", ":tru:", ":trump:", 
                        ":truss:", ":upvote:", ":uwin:", ":vdar1:", ":vdar10:", ":vdar11:", ":vdar12:", ":vdar13:", ":vdar2:", ":vdar3:", ":vdar4:", ":vdar5:", ":vdar6:", 
                        ":vdar7:", ":vdar8:", ":vdar9:", ":vithusan:", ":whitespace:", ":wonk:", ":wow:", ":wreckingball:", ":wtf:", ":wtfdiagram:", ":wutface:", 
                        ":yash:", ":yiqing:", ":zak:"]
